config/manager/kustomization.yaml
Change the newName: var to point at openstack-k8s-operators instead of dkehn.
=> change the configMapGenerator

.github/workflows/build-designate-operator.yaml
We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.
=> Drop paths-ignore from build operator workflow

.github/workflows/build-designate-operator.yaml
We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145
=> Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

controllers/designateapi_controller.go
The current logic ignores the error but it should be returned so that the error can be detected in the reconciler.
=> Return error in ConfigMap creation

templates/designateapi/config/designate.conf
The current settings define the value exactly same as the service defaults, thus can be removed. This allows us to reduce number of parameters we have to maintain.
=> Drop redundant quota_* options

.gitignore
We can exclude the top-directory instead of using the pattern which can match subdirectories.
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>
=> Simplify pattern to exclude bin

controllers/designateapi_controller.go, templates/designateapi/config/designate.conf
Internal endpoint is meant for interaction between services. This ensures designate uses internal endpoints when it sends requests to the other services.
=>  Use internal endpoint to interact with Keystone

.golangci.yaml, .pre-commit-config.yaml, Makefile, controllers/designateapi_controller.go
This PR replace deprecated go-linter using
revive (https://golangci-lint.run/usage/linters/#revive).
We will add "ginkgolinter" in follow up patch once we merged add pre-commit job in openshift/releases.
If we add "ginkgolinter" in this patch then it's causes below issue [1]
```
level=info msg="[config_reader] Config search paths: [./ /home/prow/go/src/github.com/openstack-k8s-operators/dataplane-operator /home/prow/go/src/github.com/openstack-k8s-operators /home/prow/go/src/github.com /home/prow/go/src /home/prow/go /home/prow /home /]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=error msg="Running error: unknown linters: 'ginkgolinter', run 'golangci-lint help linters' to see the list of supported linters"
```
This patch also Remove fmt dependency from make …
=> Add revive to golanci

config/samples/designate_v1beta1_designateapi.yaml
We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib
=> Replace TripleO images by TCIB images

api/bases/designate.openstack.org_designateapis.yaml, api/bases/designate.openstack.org_designates.yaml, api/v1beta1/designate_types.go, api/v1beta1/designateapi_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/designate.openstack.org_designateapis.yaml, config/crd/bases/designate.openstack.org_designates.yaml, controllers/designate_controller.go, controllers/designateapi_controller.go
These items presented in CR status are not really used. Endpoints can be discovered using Keystone and we have no use case to require service id.
=> Remove endpoint url and keystone service id from status

controllers/designate_controller.go
This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.
=> Watch RBAC resources to trigger reconcile

pkg/designate/const.go
This constant is no longer used since we removed admin endpoints.
=> Remove unused constant for admin endpoint

api/bases/designate.openstack.org_designatecentrals.yaml, api/bases/designate.openstack.org_designatemdnses.yaml, api/bases/designate.openstack.org_designateproducers.yaml, api/bases/designate.openstack.org_designates.yaml, api/bases/designate.openstack.org_designateworkers.yaml, api/v1beta1/designate_types.go, api/v1beta1/designatecentral_types.go, api/v1beta1/designatemdns_types.go, api/v1beta1/designateproducer_types.go, api/v1beta1/designateworker_types.go, config/crd/bases/designate.openstack.org_designatecentrals.yaml, config/crd/bases/designate.openstack.org_designatemdnses.yaml, config/crd/bases/designate.openstack.org_designateproducers.yaml, config/crd/bases/designate.openstack.org_designates.yaml, config/crd/bases/designate.openstack.org_designateworkers.yaml, config/crd/kustomization.yaml, config/manifests/bases/designate-operator.clusterserviceversion.yaml
CSV does not contain some CRs recently added. This ensures all CRs are listed.
=> Fix a few missing CRs in csv

pkg/designate/const.go, pkg/designate/dbsync.go, pkg/designateapi/const.go, pkg/designateapi/deployment.go, pkg/designatecentral/const.go, pkg/designatecentral/deployment.go, pkg/designatemdns/const.go, pkg/designatemdns/deployment.go, pkg/designateproducer/const.go, pkg/designateproducer/deployment.go, pkg/designateworker/const.go, pkg/designateworker/deployment.go
The previous attempt added the bind mount to expose the config file to the default path but it did not remove the environment variable actually from pods.
=> Remove KOLLA_CONFIG_FILE environment variable

api/bases/designate.openstack.org_designateapis.yaml, api/bases/designate.openstack.org_designatebackendbind9s.yaml, api/bases/designate.openstack.org_designatecentrals.yaml, api/bases/designate.openstack.org_designatemdnses.yaml, api/bases/designate.openstack.org_designateproducers.yaml, api/bases/designate.openstack.org_designates.yaml, api/bases/designate.openstack.org_designateworkers.yaml, api/v1beta1/common_types.go, api/v1beta1/designate_types.go, config/crd/bases/designate.openstack.org_designateapis.yaml, config/crd/bases/designate.openstack.org_designatebackendbind9s.yaml, config/crd/bases/designate.openstack.org_designatecentrals.yaml, config/crd/bases/designate.openstack.org_designatemdnses.yaml, config/crd/bases/designate.openstack.org_designateproducers.yaml, config/crd/bases/designate.openstack.org_designates.yaml, config/crd/bases/designate.openstack.org_designateworkers.yaml, pkg/designatebackendbind9/deployment.go, templates/designate/config/rndc.conf
There are a few locations where designate is mispelled that might cause confusion or configuration errors.
=> Fix transposed characters for designate

controllers/designate_controller.go, go.mod, go.sum, pkg/designate/common.go
The lib-common/modules/database is moved to mariadb-operator/api to remove a circular dependency.
=> Use database helpers from mariadb-operator/api

.prow_ci.env, Makefile, api/v1beta1/common_types.go, config/default/manager_default_images.yaml, config/manager/kustomization.yaml, config/manifests/bases/designate-operator.clusterserviceversion.yaml
This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
(NOTE: this currently requires a secure registry)
=> Support disconnected network environments

controllers/designate_controller.go, controllers/designateapi_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateworker_controller.go, main.go
This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-05-18T02:00:28+03:00       INFO    Controllers.KeystoneAPI Reconciled Service init successfully    {"controller": "keystoneapi", "controllerGroup": "keystone.openstack.org", "controllerKind":"KeystoneAPI", "KeystoneAPI": {"name":"keystone","namespace":"openstack"}, "namespace": "openstack", "name": "keystone", "reconcileID": "512a4d9b-f31d-4fa4-a4cc-cd6c13e4455d"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.
*example logs …
=> switch to structured logging

OWNERS, OWNERS_ALIASES
This extended list of approvers should make it easier to integrate PRs, and it aligns with the approvers list of octavia-operator, which is similar in it's team structure.
=> Extend list of approvers to network-approvers

main.go
The Designate LeaderElectionID was updated [0] by mistake to the same ID as the Octavia operator [1], it creates a race condition when both operators start, they both try to acquire the same resource. Fixing this issue by restoring the previous ID.
[0] https://github.com/openstack-k8s-operators/designate-operator/commit/f8967a4cf183f226992f439cfe926cbf7f928d96#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R83
[1] https://github.com/openstack-k8s-operators/octavia-operator/blob/c143deb4c63f4696e8d613611087aae48613a4db/main.go#L102
=> Restore Designate LeaderElectionID

.pre-commit-config.yaml, controllers/designate_controller.go, controllers/designateapi_controller.go, controllers/designatebackendbind9_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateunbound_controller.go, controllers/designateworker_controller.go, controllers/suite_test.go, go.mod, pkg/designate/dbsync.go, pkg/designateunbound/deployment.go
* removed unused func params
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* various small style fixes found by the linter
* the linter also showed that we the network attachments are unused. This was probably missed during some refactor as the network attachments was gathered but isn't passed anywhere. Based on the controller logic we can pass it to the dbsync job.
=> Ensure golangci-lint runs on all files

api/go.mod, api/go.sum, api/v1beta1/designate_webhook.go, go.mod, go.sum
Can also be called from the openstack-operator webhook on the DesignateSpecCore, like for other operators in [1].
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/d2703d3a321c979dacaca95b5d4a634bf116e0db/apis/core/v1beta1/openstackcontrolplane_webhook.go#L181
=> Add webhook to validate service override endpoint type

.prow_ci.env, Dockerfile, Makefile, config/manifests/bases/designate-operator.clusterserviceversion.yaml
- Changed the build image to ubi9/go-toolkit
- Changed the base image to ubi9/minimal
- Added the default GO_BUILD_EXTRA_ARGS="-tags strictfipsruntime"
- Added the GO_BUILD_EXTRA_ENV_ARGS build argument to allow custom build arguments at build time. It defaults to "CGO_ENABLED=1 GO111MODULE=on"
- Those default parameters have been added to enable FIPS compliance
- Fixed indentation
- Removed TARGETOS and TARGETARCH env vars.
- Added DOCKER_BUILD_ARGS variable in Makefile to pass custom parameters during podman build
- Added export FAIL_FIPS_CHECK=true in .prow_ci.env file
- Add the FIPS compliant feature flag to the operator.
=> This change adds requirements for FIPS

Makefile
specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk
update to 1.31 version
=> update Makefile to include local bin operator-sdk

api/v1beta1/common_types.go, config/default/manager_default_images.yaml
Prior to a fix to the mariadb operator, we were unable to properly initialize the database for the designate. This has been resolved so the current container images should work.
=> Update container images

templates/designate/config/designate.conf
This patch enables the Secure RBAC policies to include both the Keystone default roles, and Keystone scoped tokens.
[1] https://docs.openstack.org/designate/latest/admin/policy.html#enabling-keystone-default-roles-and-scoped-tokens
=> Enable Secure RBAC

controllers/designate_controller.go, controllers/designateapi_controller.go, controllers/designatebackendbind9_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateunbound_controller.go, controllers/designateworker_controller.go
Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler
=> Return nil error in case NotFound and to use RequeueAfter

config/manifests/bases/designate-operator.clusterserviceversion.yaml, controllers/designatemdns_controller.go
Designate Mdns panicked after trying to access addresses in a few lines where it got nil pointer.
This patch fixes it by making sure the address it not nil.
=> Fix mdns replicas nil

pkg/designate/initcontainer.go, templates/designate/bin/init.sh, templates/designate/config/init_setup.sh
We do not support, nor do we have any plan to support DNS servers other than bind9 for the forseeable future. While we cannot remove it from the API, this patch removes it from the places it is used to avoid confusion or errorneous values from causing unexpected behaviour.
=> Remove backendtype uses

controllers/designate_controller.go, pkg/designate/const.go, pkg/designate/rndckeygenerator.go
This PR adds the option of rndc key files generation. Given the bind replicas value, it allows Designate operator to either create or delete rndc/bind secrets.
=> Generate an rndc key per bind instance

api/bases/designate.openstack.org_designates.yaml, api/v1beta1/designate_types.go, config/crd/bases/designate.openstack.org_designates.yaml, config/rbac/role.yaml, controllers/designate_controller.go, controllers/designatemdns_controller.go, controllers/designateworker_controller.go, pkg/designate/bind_ctrl_network.go, pkg/designate/const.go, pkg/designate/network_consts.go, pkg/designate/network_parameters.go, pkg/designatemdns/daemonset.go, pkg/designatemdns/volumes.go
The designate miniDNS needs a predictable IP mechanism, as it is a
daemonset and will use the list of available workers to generate a list
of IPs that are valid for the designate network attachment's CIDR range
but do not overlap with the address range defined in the attachment's
IPAM config.
This patch adds it.
=> Implement predictable IP generation for miniDNS

controllers/designate_controller.go, pkg/designate/bind_ctrl_network.go, pkg/designate/const.go
Generate and manage predictable IPs for each member of the bind
statefulset and store in it's own predictable IPs config map.
The reason it needs to be it's own map is that we do not want to cause
minidns to restart if a scaling change occurs on mind - nor do we want
minidns scale changes to affect bind pods.
=> Generate predictable IPs for bind stateful set

controllers/designateapi_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateworker_controller.go
It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```
=> Make sure to log error in findObjectsForSrc()

config/samples/designate_v1beta1_designate.yaml, config/samples/designate_v1beta1_designate_tls.yaml, tests/kuttl/common/designate_nad.yaml, tests/kuttl/tests/basic/deploy/kustomization.yaml, tests/kuttl/tests/designate_tls/01-nad.yaml, tests/kuttl/tests/designate_tls/02-deploy.yaml
Adds a NAD so functionality such as predictable IPs and bind pool generation can be tested via kuttl. This NAD is not appropriate iif kuttl tests use multiple openshift workers as the NAD is a bridge type.
=> Add a test NAD to allow more code paths to run during testing

api/go.mod, api/go.sum, controllers/designate_controller.go, controllers/designateapi_controller.go, controllers/designatebackendbind9_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateunbound_controller.go, controllers/designateworker_controller.go, go.mod, go.sum
For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.
Jira: https://issues.redhat.com/browse/OSPRH-8680
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579
=> Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

api/v1beta1/common_types.go, api/v1beta1/designate_types.go, api/v1beta1/zz_generated.deepcopy.go, controllers/designate_controller.go, pkg/designate/dbsync.go, pkg/designateapi/deployment.go, pkg/designatebackendbind9/deployment.go, pkg/designatecentral/deployment.go, pkg/designatemdns/daemonset.go, pkg/designateproducer/deployment.go, pkg/designateunbound/deployment.go, pkg/designateworker/deployment.go
nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)
=> Ensure nodeSelector logic is consistent for all operators 

api/bases/designate.openstack.org_designatecentrals.yaml, api/bases/designate.openstack.org_designateproducers.yaml, api/bases/designate.openstack.org_designates.yaml, api/v1beta1/designate_types.go, api/v1beta1/designatecentral_types.go, api/v1beta1/designateproducer_types.go, config/crd/bases/designate.openstack.org_designatecentrals.yaml, config/crd/bases/designate.openstack.org_designateproducers.yaml, config/crd/bases/designate.openstack.org_designates.yaml
Since RedisServiceName has a default, lets make it optional. Parameters which are required with a default is a contradiction.
Also adds listType annotation to RedisHostIPs.
=> Make RedisServiceName optional and add listType annotations

api/bases/designate.openstack.org_designateapis.yaml, api/bases/designate.openstack.org_designates.yaml, api/v1beta1/common_types.go, api/v1beta1/designate_types.go, api/v1beta1/designate_webhook.go, api/v1beta1/designateapi_types.go, config/crd/bases/designate.openstack.org_designateapis.yaml, config/crd/bases/designate.openstack.org_designates.yaml, controllers/designate_controller.go, controllers/designateapi_controller.go, templates/designateapi/config/httpd.conf
This patch adds an apiTimeout field to the DesignateSpecCore to DesignateSpec, to allow a configuration of the timeouts for HAProxy and Apache.
Inherit from the controller in case it is not specified by the user.
Jira: https://issues.redhat.com/browse/OSPRH-10963
=> Add configurable httpd timeout

pkg/designate/generate_bind9_pools_yaml.go, templates/designatepoolmanager/config/pools.yaml.tmpl, tests/functional/designate_controller_test.go
So far we were generating a pools.yaml file with rndc_config_file config option, but it should have been rndc_key_file, with the correct path.
This patch fixes it.
=> Fix pools.yaml rndc_key_file config typo

controllers/designate_controller.go, pkg/designate/generate_bind9_pools_yaml.go, pkg/designate/pool_update.go, tests/functional/designate_controller_test.go
The pool update job was not launched correctly because all of the job instances had the same name. As Kubernetes requires names be unique across all API versions of the same resource, the job was only triggered once.
This patch adds the jobs a unix timestamp suffix to overcome that problem.
It also sorts the pool resources to create a comparable hash between jobs.
=> Fix pool update job

api/v1beta1/designate_types.go, config/default/manager_default_images.yaml
There is a env-var->go-var transform in openstack-operator that matches env vars to go vars based on _ breaks in the name. Our spec wants NetUtilsImage which requires NET_UTILS_IMAGE, not NETUTILS_IMAGE to get the correct camel case. This patch keeps things consistent across the repos.
=> Update envvar name for netutils container image

controllers/designatebackendbind9_controller.go, pkg/designatebackendbind9/deployment.go
The `resource.MustParse` function was previously used by the operator to process the `storageSize` request provided by the top-level CR. However, even though `defer()` and `recover()` can be used to handle the `panic()` generated by that function in case of a wrong user input, that approach doesn't seem to work properly and the operator crashes without any chance to recover. The `ParseQuantity` implementation returns an error instead of `panic()`, and it can be easily caught at the operator level. This change moves away from the `MustParse` usage and relies on the `ParseQuantity` mechanism.
=> Do not use MustParse to process PVC size

controllers/designate_controller.go, pkg/designate/const.go, pkg/designate/generate_bind9_pools_yaml.go, tests/functional/designate_controller_test.go
So far we only allowed using NsRecords via a ConfigMap.
While using nsRecordsConfigMap works, creating/modifying it does not trigger another run of the reconciliation loop. That means the user can modify the ns records config map and wait for a long time without the changes to take affect from Designate perspective.
This patch adds support for adding nsRecords via Designate CR/csv, which will take precedence over the ns records config map. If nsRecords is not configured in the Designate CR, it will fall back to the configmap.
=> Add support to NsRecords via CR

controllers/designate_controller.go
So far we did not have a default value for controlNetworkName, which resulted in Designate network attachment not being found in some deployments.
This patch adds a hard-coded default value for Designate network attachment in case one was not defined in the CR.
=> [OSPRH-14758] Fix controlNetworkName requires default value

controllers/designate_controller.go, controllers/designateapi_controller.go, controllers/designatebackendbind9_controller.go, controllers/designatecentral_controller.go, controllers/designatemdns_controller.go, controllers/designateproducer_controller.go, controllers/designateunbound_controller.go, controllers/designateworker_controller.go
Currently we use deferred call to always update the status field when Reconciler call exits, which seems correct for any other error except Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16954](https://issues.redhat.com//browse/OSPRH-16954)
=> Do not update status when reconciler exits due to panic

controllers/designateapi_controller.go, go.mod, go.sum, tests/functional/designateapi_controller_test.go
Adds watches of the Nova controller on the KeystoneAPI status to reconcile if e.g. the endpoint list changes. This triggers setting the new KeystoneAuthURL on the sub components to update their configuration.
Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/591
Jira: [OSPRH-16994](https://issues.redhat.com//browse/OSPRH-16994)
=> Watch KeystoneAPI status updates to reconcile

pkg/designatemdns/statefulset.go, templates/common/setipalias.py, templates/designatemdns/bin/setipalias.sh
Have mDNS listen and use the predictable IP for apps expecting replies from mDNS to be from the same address that was used for the request.
Jira: [OSPRH-15638](https://issues.redhat.com//browse/OSPRH-15638)
=> 18.0 fr3 Set the listen address to the predictable IP for mdns

templates/designate/config/designate.conf
We need to disable RBAC for now as the operator had several configuration challenges that prevented distributing policy.json updates. This commit can be reverted once that has been resolved.
=> 18.0 fr3 Disable RBAC checks temporarily

controllers/designate_controller.go
Fixes a bug where we update a hash before the job that it is supposed to trigger the poolupdatejob before it succeeds making the controller skip further attempts. This leads to a broken internal configuration in designate that won't be rectified until something changes the contents of a the pools.yaml file like scaling changes for mDNS or the BIND9 instances or the values in nsRecords.
=> Don't update pool update hash until job is successful

controllers/designate_controller.go
Fixes a bug where we update a hash before the job that it is supposed to trigger the poolupdatejob before it succeeds making the controller skip further attempts. This leads to a broken internal configuration in designate that won't be rectified until something changes the contents of a the pools.yaml file like scaling changes for mDNS or the BIND9 instances or the values in nsRecords.
=> [18.0-fr3] Don't update pool update hash until job is successful

controllers/designateunbound_controller.go, tests/kuttl/tests/designate_tls/05-assert.yaml, tests/kuttl/tests/designate_tls/05-deploy.yaml
Unbound doesn't like "true" as a configuration value for stub-prime and stub-first so change to "yes".
Jira: [OSPRH-19380](https://issues.redhat.com//browse/OSPRH-19380)
=> Change stubzone generated defaults from true to yes

controllers/designateunbound_controller.go, tests/kuttl/tests/designate_tls/05-assert.yaml, tests/kuttl/tests/designate_tls/05-deploy.yaml
Unbound doesn't like "true" as a configuration value for stub-prime and stub-first so change to "yes".
Jira #[OSPRH-19380](https://issues.redhat.com//browse/OSPRH-19380)
=> [18.0-fr3] Change stubzone generated defaults from true to yes
